### ISSUE TITLE
[Question] Adding mod guide book via API

### ISSUE THREAD

**Issue by maxanier** [PenguinSquad/Enchiridion#82]
I'm thinking about creating a GuideBook for my mod Vampirism.
It looks like I can just create a book in game using Enchiridion, export it and then register it in code using Enchiridon's API.

But it looks like the API can do more things e.g. using templates (ITemplate) to display different texts depending on the configuration of a my mod or execute code when a button is pressed (IButtonAction)
Unfortunately I can't quite understand how to use those things.
Is there a open source mod out there that uses those features or did I misunderstand what they are designed to do?

**Comment by joshiejack** [comment]
My other mod Progression actually uses a couple of these. 

https://github.com/joshiejack/Progression/tree/master/src/main/java/joshie/progression/plugins/enchiridion

**Comment by maxanier** [comment]
Sorry for keeping this open so long, I did not have much time lately.
Unfortunately that also the reason why I've decided to go with GuideAPI.
Enchiridion looks a loot cooler and more user friendly, but I already had a GuideAPI book for an older version of Vampirism, so it should be a lot faster to readd.

**Comment by joshiejack** [comment]
GuideAPI is aimed at mod devs, where as this more for pack devs. Good choice =P
