### ISSUE TITLE
I can't edit Progression support "quest" description

### ISSUE THREAD

**Issue by majix560** [PenguinSquad/Enchiridion#83]
I am using both Enchiridion and Progression in my modpack "[Psionics](http://minecraft.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.atlauncher.com%252fpack%252fPsionics%252f)".
I am wanting to use Enchiridion to provide guides on the mods and the official server.
And to use Enchiridion + Progression for questing.
However I find it impossible to edit the descriptive text of the "quest" criteria as
1. There is no way to jump x pages forward/backward
2. Inserting a next/previous page button doesn't go to the wanted page.
3. Quest page is on a negative page, editing nav bar shows equivalent positive page numbers.

I must vehemently request that you add a "Jump to page..." function to the editor,
and fix the nav bar showing positive page numbers in the millions when it should be showing the negative versions of the same page numbers.

Only thing this issue means is that I can't use Enchiridion's "HQM Clone" template with Progression.
Though I am not experiencing any other issues in Progression in and of its self, nor outside of the HQM template in Enchiridion.

**Comment by joshiejack** [comment]
The description page is directly after the page for me. Which you can navigate to by clicking on it using the nav bar at the bottom. At least it was last time I looked. I'll have to double check some other time.

**Comment by majix560** [comment]
like I said, the nav bar timeline gets put on the positively numbered version of the quest page number.
And the quest page is actually negatively numbered.
I am experiencing this on Alpha-2.10.0 of my modpack, Psionics (linked in original post).

**Comment by majix560** [comment]
@joshiejack did you not have time yet to try? or did you miss my (previous) reply?

**Comment by joshiejack** [comment]
Probably look in to it tomorrow, if not then Monday.

**Comment by majix560** [comment]
Soooo...
I'll give you the benefit of the doubt for now and assume you took a look at it and are working on a fix.

**Comment by joshiejack** [comment]
More like was focusing on other things. Progression related things (although this is ench), are really low on my priority list, that's why I'm very slow to do things. (I don't find them fun :/)

**Comment by majix560** [comment]
Hopefully the update to Progression means you'll get started on this soon

**Comment by majix560** [comment]
With the latest Progression version (version 1.10.2-0.6.8) put inside version Alpha-3.5.0 of my pack I can now edit the description of individual quests as now the pages show up properly in the timeline.
However I am still having another similar issue.
The only way I can currently get to the main quest book description page is to "create" a negatively numbered page and then delete it.
When I do that it moves me to the content page for the right-hand side main description of the HQM clone quest book.
Now that I think about it, it seems that only the creation of the front page or so is handled by Enchiridion templates, the rest is created by Progression dynamically.
I know this because I peeked at the HQM clone template's source.
So that would probably mean this belonged solely in Progression git if not both Progression and Enchiridion gits

**Comment by majix560** [comment]
Actually it seems that it only works as intended in single player, tried again on my server and I still can't get to the question description page on the server.
@joshiejack
